spring.application.name=eventify
server.port=8080

# Swagger UI disponible en http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Activa/desactiva los datos iniciales. Para probar catalogo vacio usa: eventify.seed.enabled=false
eventify.seed.enabled=true
