spring.application.name=eventify
spring.datasource.url=jdbc:h2:file:./data/eventifydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Seeder
 eventify.seed.enabled=true
