-- Categorias base
INSERT INTO categories (name, description) VALUES ('Concerts', 'Eventos musicales y conciertos en vivo');
INSERT INTO categories (name, description) VALUES ('Workshops', 'Talleres practicos y formativos');
INSERT INTO categories (name, description) VALUES ('Conferences', 'Conferencias academicas y empresariales');
INSERT INTO categories (name, description) VALUES ('Sports', 'Eventos deportivos');
INSERT INTO categories (name, description) VALUES ('Gastronomy', 'Experiencias gastronomicas');
INSERT INTO categories (name, description) VALUES ('Festivals', 'Festivales culturales y masivos');
INSERT INTO categories (name, description) VALUES ('Theater', 'Obras y experiencias escenicas');

-- Venues base
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Movistar Arena', 'Diagonal 61C # 26-36', 14000, 'Bogota');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Centro de Convenciones', 'Calle 41 # 55-80', 1200, 'Medellin');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Teatro Metropolitano', 'Avenida 2N # 7-18', 900, 'Cali');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Parque Simon Bolivar', 'Avenida Calle 63 # 60-70', 50000, 'Bogota');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Auditorio Caribe', 'Carrera 54 # 74-127', 2200, 'Barranquilla');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Centro Cultural Andino', 'Carrera 35 # 48-21', 650, 'Bucaramanga');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Plaza Mayor', 'Calle 41 # 55-80', 5000, 'Medellin');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Teatro Nacional', 'Calle 71 # 10-25', 700, 'Bogota');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Coliseo del Cafe', 'Avenida Kevin Angel # 65-100', 3500, 'Manizales');
INSERT INTO venues (nombre, direccion, capacidad, ciudad) VALUES ('Centro Historico', 'Plaza de la Aduana # 1-01', 1800, 'Cartagena');

-- 200 eventos variados ordenables y filtrables
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Concierto de ROCK', '2026-01-01', 'Actividad 1 en Bogota con categoria Concerts', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (1, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 2', '2026-01-02', 'Actividad 2 en Medellin con categoria Workshops', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (2, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 3', '2026-01-03', 'Actividad 3 en Cali con categoria Conferences', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (3, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 4', '2026-01-04', 'Actividad 4 en Bogota con categoria Sports', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (4, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 5', '2026-01-05', 'Actividad 5 en Barranquilla con categoria Gastronomy', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (5, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 6', '2026-01-06', 'Actividad 6 en Bucaramanga con categoria Festivals', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (6, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 7', '2026-01-07', 'Actividad 7 en Medellin con categoria Theater', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (7, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 8', '2026-01-08', 'Actividad 8 en Bogota con categoria Concerts', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (8, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 9', '2026-01-09', 'Actividad 9 en Manizales con categoria Workshops', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (9, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 10', '2026-01-10', 'Actividad 10 en Cartagena con categoria Conferences', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (10, 3);
INSERT INTO events_categories (event_id, category_id) VALUES (10, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 11', '2026-01-11', 'Actividad 11 en Bogota con categoria Sports', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (11, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 12', '2026-01-12', 'Actividad 12 en Medellin con categoria Gastronomy', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (12, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 13', '2026-01-13', 'Actividad 13 en Cali con categoria Festivals', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (13, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 14', '2026-01-14', 'Actividad 14 en Bogota con categoria Theater', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (14, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 15', '2026-01-15', 'Actividad 15 en Barranquilla con categoria Concerts', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (15, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 16', '2026-01-16', 'Actividad 16 en Bucaramanga con categoria Workshops', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (16, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 17', '2026-01-17', 'Actividad 17 en Medellin con categoria Conferences', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (17, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 18', '2026-01-18', 'Actividad 18 en Bogota con categoria Sports', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (18, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 19', '2026-01-19', 'Actividad 19 en Manizales con categoria Gastronomy', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (19, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 20', '2026-01-20', 'Actividad 20 en Cartagena con categoria Festivals', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (20, 6);
INSERT INTO events_categories (event_id, category_id) VALUES (20, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 21', '2026-01-21', 'Actividad 21 en Bogota con categoria Theater', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (21, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 22', '2026-01-22', 'Actividad 22 en Medellin con categoria Concerts', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (22, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 23', '2026-01-23', 'Actividad 23 en Cali con categoria Workshops', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (23, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 24', '2026-01-24', 'Actividad 24 en Bogota con categoria Conferences', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (24, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 25', '2026-01-25', 'Actividad 25 en Barranquilla con categoria Sports', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (25, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 26', '2026-01-26', 'Actividad 26 en Bucaramanga con categoria Gastronomy', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (26, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 27', '2026-01-27', 'Actividad 27 en Medellin con categoria Festivals', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (27, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 28', '2026-01-28', 'Actividad 28 en Bogota con categoria Theater', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (28, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 29', '2026-02-01', 'Actividad 29 en Manizales con categoria Concerts', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (29, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 30', '2026-02-02', 'Actividad 30 en Cartagena con categoria Workshops', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (30, 2);
INSERT INTO events_categories (event_id, category_id) VALUES (30, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 31', '2026-02-03', 'Actividad 31 en Bogota con categoria Conferences', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (31, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 32', '2026-02-04', 'Actividad 32 en Medellin con categoria Sports', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (32, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 33', '2026-02-05', 'Actividad 33 en Cali con categoria Gastronomy', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (33, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 34', '2026-02-06', 'Actividad 34 en Bogota con categoria Festivals', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (34, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 35', '2026-02-07', 'Actividad 35 en Barranquilla con categoria Theater', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (35, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 36', '2026-02-08', 'Actividad 36 en Bucaramanga con categoria Concerts', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (36, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 37', '2026-02-09', 'Actividad 37 en Medellin con categoria Workshops', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (37, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 38', '2026-02-10', 'Actividad 38 en Bogota con categoria Conferences', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (38, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 39', '2026-02-11', 'Actividad 39 en Manizales con categoria Sports', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (39, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 40', '2026-02-12', 'Actividad 40 en Cartagena con categoria Gastronomy', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (40, 5);
INSERT INTO events_categories (event_id, category_id) VALUES (40, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 41', '2026-02-13', 'Actividad 41 en Bogota con categoria Festivals', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (41, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 42', '2026-02-14', 'Actividad 42 en Medellin con categoria Theater', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (42, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 43', '2026-02-15', 'Actividad 43 en Cali con categoria Concerts', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (43, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 44', '2026-02-16', 'Actividad 44 en Bogota con categoria Workshops', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (44, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 45', '2026-02-17', 'Actividad 45 en Barranquilla con categoria Conferences', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (45, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 46', '2026-02-18', 'Actividad 46 en Bucaramanga con categoria Sports', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (46, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 47', '2026-02-19', 'Actividad 47 en Medellin con categoria Gastronomy', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (47, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 48', '2026-02-20', 'Actividad 48 en Bogota con categoria Festivals', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (48, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 49', '2026-02-21', 'Actividad 49 en Manizales con categoria Theater', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (49, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 50', '2026-02-22', 'Actividad 50 en Cartagena con categoria Concerts', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (50, 1);
INSERT INTO events_categories (event_id, category_id) VALUES (50, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 51', '2026-02-23', 'Actividad 51 en Bogota con categoria Workshops', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (51, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 52', '2026-02-24', 'Actividad 52 en Medellin con categoria Conferences', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (52, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 53', '2026-02-25', 'Actividad 53 en Cali con categoria Sports', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (53, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 54', '2026-02-26', 'Actividad 54 en Bogota con categoria Gastronomy', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (54, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 55', '2026-02-27', 'Actividad 55 en Barranquilla con categoria Festivals', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (55, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 56', '2026-02-28', 'Actividad 56 en Bucaramanga con categoria Theater', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (56, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 57', '2026-03-01', 'Actividad 57 en Medellin con categoria Concerts', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (57, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 58', '2026-03-02', 'Actividad 58 en Bogota con categoria Workshops', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (58, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 59', '2026-03-03', 'Actividad 59 en Manizales con categoria Conferences', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (59, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 60', '2026-03-04', 'Actividad 60 en Cartagena con categoria Sports', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (60, 4);
INSERT INTO events_categories (event_id, category_id) VALUES (60, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 61', '2026-03-05', 'Actividad 61 en Bogota con categoria Gastronomy', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (61, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 62', '2026-03-06', 'Actividad 62 en Medellin con categoria Festivals', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (62, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 63', '2026-03-07', 'Actividad 63 en Cali con categoria Theater', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (63, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 64', '2026-03-08', 'Actividad 64 en Bogota con categoria Concerts', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (64, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 65', '2026-03-09', 'Actividad 65 en Barranquilla con categoria Workshops', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (65, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 66', '2026-03-10', 'Actividad 66 en Bucaramanga con categoria Conferences', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (66, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 67', '2026-03-11', 'Actividad 67 en Medellin con categoria Sports', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (67, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 68', '2026-03-12', 'Actividad 68 en Bogota con categoria Gastronomy', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (68, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 69', '2026-03-13', 'Actividad 69 en Manizales con categoria Festivals', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (69, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 70', '2026-03-14', 'Actividad 70 en Cartagena con categoria Theater', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (70, 7);
INSERT INTO events_categories (event_id, category_id) VALUES (70, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 71', '2026-03-15', 'Actividad 71 en Bogota con categoria Concerts', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (71, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 72', '2026-03-16', 'Actividad 72 en Medellin con categoria Workshops', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (72, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 73', '2026-03-17', 'Actividad 73 en Cali con categoria Conferences', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (73, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 74', '2026-03-18', 'Actividad 74 en Bogota con categoria Sports', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (74, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 75', '2026-03-19', 'Actividad 75 en Barranquilla con categoria Gastronomy', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (75, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 76', '2026-03-20', 'Actividad 76 en Bucaramanga con categoria Festivals', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (76, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 77', '2026-03-21', 'Actividad 77 en Medellin con categoria Theater', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (77, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 78', '2026-03-22', 'Actividad 78 en Bogota con categoria Concerts', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (78, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 79', '2026-03-23', 'Actividad 79 en Manizales con categoria Workshops', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (79, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 80', '2026-03-24', 'Actividad 80 en Cartagena con categoria Conferences', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (80, 3);
INSERT INTO events_categories (event_id, category_id) VALUES (80, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 81', '2026-03-25', 'Actividad 81 en Bogota con categoria Sports', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (81, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 82', '2026-03-26', 'Actividad 82 en Medellin con categoria Gastronomy', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (82, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 83', '2026-03-27', 'Actividad 83 en Cali con categoria Festivals', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (83, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 84', '2026-03-28', 'Actividad 84 en Bogota con categoria Theater', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (84, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 85', '2026-04-01', 'Actividad 85 en Barranquilla con categoria Concerts', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (85, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 86', '2026-04-02', 'Actividad 86 en Bucaramanga con categoria Workshops', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (86, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 87', '2026-04-03', 'Actividad 87 en Medellin con categoria Conferences', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (87, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 88', '2026-04-04', 'Actividad 88 en Bogota con categoria Sports', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (88, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 89', '2026-04-05', 'Actividad 89 en Manizales con categoria Gastronomy', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (89, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 90', '2026-04-06', 'Actividad 90 en Cartagena con categoria Festivals', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (90, 6);
INSERT INTO events_categories (event_id, category_id) VALUES (90, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 91', '2026-04-07', 'Actividad 91 en Bogota con categoria Theater', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (91, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 92', '2026-04-08', 'Actividad 92 en Medellin con categoria Concerts', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (92, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 93', '2026-04-09', 'Actividad 93 en Cali con categoria Workshops', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (93, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 94', '2026-04-10', 'Actividad 94 en Bogota con categoria Conferences', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (94, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 95', '2026-04-11', 'Actividad 95 en Barranquilla con categoria Sports', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (95, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 96', '2026-04-12', 'Actividad 96 en Bucaramanga con categoria Gastronomy', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (96, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 97', '2026-04-13', 'Actividad 97 en Medellin con categoria Festivals', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (97, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 98', '2026-04-14', 'Actividad 98 en Bogota con categoria Theater', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (98, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 99', '2026-04-15', 'Actividad 99 en Manizales con categoria Concerts', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (99, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 100', '2026-04-16', 'Actividad 100 en Cartagena con categoria Workshops', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (100, 2);
INSERT INTO events_categories (event_id, category_id) VALUES (100, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 101', '2026-04-17', 'Actividad 101 en Bogota con categoria Conferences', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (101, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 102', '2026-04-18', 'Actividad 102 en Medellin con categoria Sports', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (102, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 103', '2026-04-19', 'Actividad 103 en Cali con categoria Gastronomy', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (103, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 104', '2026-04-20', 'Actividad 104 en Bogota con categoria Festivals', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (104, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 105', '2026-04-21', 'Actividad 105 en Barranquilla con categoria Theater', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (105, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 106', '2026-04-22', 'Actividad 106 en Bucaramanga con categoria Concerts', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (106, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 107', '2026-04-23', 'Actividad 107 en Medellin con categoria Workshops', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (107, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 108', '2026-04-24', 'Actividad 108 en Bogota con categoria Conferences', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (108, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 109', '2026-04-25', 'Actividad 109 en Manizales con categoria Sports', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (109, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 110', '2026-04-26', 'Actividad 110 en Cartagena con categoria Gastronomy', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (110, 5);
INSERT INTO events_categories (event_id, category_id) VALUES (110, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 111', '2026-04-27', 'Actividad 111 en Bogota con categoria Festivals', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (111, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 112', '2026-04-28', 'Actividad 112 en Medellin con categoria Theater', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (112, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 113', '2026-05-01', 'Actividad 113 en Cali con categoria Concerts', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (113, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 114', '2026-05-02', 'Actividad 114 en Bogota con categoria Workshops', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (114, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 115', '2026-05-03', 'Actividad 115 en Barranquilla con categoria Conferences', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (115, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 116', '2026-05-04', 'Actividad 116 en Bucaramanga con categoria Sports', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (116, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 117', '2026-05-05', 'Actividad 117 en Medellin con categoria Gastronomy', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (117, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 118', '2026-05-06', 'Actividad 118 en Bogota con categoria Festivals', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (118, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 119', '2026-05-07', 'Actividad 119 en Manizales con categoria Theater', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (119, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 120', '2026-05-08', 'Actividad 120 en Cartagena con categoria Concerts', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (120, 1);
INSERT INTO events_categories (event_id, category_id) VALUES (120, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 121', '2026-05-09', 'Actividad 121 en Bogota con categoria Workshops', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (121, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 122', '2026-05-10', 'Actividad 122 en Medellin con categoria Conferences', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (122, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 123', '2026-05-11', 'Actividad 123 en Cali con categoria Sports', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (123, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 124', '2026-05-12', 'Actividad 124 en Bogota con categoria Gastronomy', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (124, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 125', '2026-05-13', 'Actividad 125 en Barranquilla con categoria Festivals', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (125, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 126', '2026-05-14', 'Actividad 126 en Bucaramanga con categoria Theater', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (126, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 127', '2026-05-15', 'Actividad 127 en Medellin con categoria Concerts', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (127, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 128', '2026-05-16', 'Actividad 128 en Bogota con categoria Workshops', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (128, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 129', '2026-05-17', 'Actividad 129 en Manizales con categoria Conferences', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (129, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 130', '2026-05-18', 'Actividad 130 en Cartagena con categoria Sports', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (130, 4);
INSERT INTO events_categories (event_id, category_id) VALUES (130, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 131', '2026-05-19', 'Actividad 131 en Bogota con categoria Gastronomy', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (131, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 132', '2026-05-20', 'Actividad 132 en Medellin con categoria Festivals', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (132, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 133', '2026-05-21', 'Actividad 133 en Cali con categoria Theater', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (133, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 134', '2026-05-22', 'Actividad 134 en Bogota con categoria Concerts', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (134, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 135', '2026-05-23', 'Actividad 135 en Barranquilla con categoria Workshops', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (135, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 136', '2026-05-24', 'Actividad 136 en Bucaramanga con categoria Conferences', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (136, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 137', '2026-05-25', 'Actividad 137 en Medellin con categoria Sports', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (137, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 138', '2026-05-26', 'Actividad 138 en Bogota con categoria Gastronomy', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (138, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 139', '2026-05-27', 'Actividad 139 en Manizales con categoria Festivals', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (139, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 140', '2026-05-28', 'Actividad 140 en Cartagena con categoria Theater', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (140, 7);
INSERT INTO events_categories (event_id, category_id) VALUES (140, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 141', '2026-06-01', 'Actividad 141 en Bogota con categoria Concerts', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (141, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 142', '2026-06-02', 'Actividad 142 en Medellin con categoria Workshops', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (142, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 143', '2026-06-03', 'Actividad 143 en Cali con categoria Conferences', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (143, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 144', '2026-06-04', 'Actividad 144 en Bogota con categoria Sports', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (144, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 145', '2026-06-05', 'Actividad 145 en Barranquilla con categoria Gastronomy', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (145, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 146', '2026-06-06', 'Actividad 146 en Bucaramanga con categoria Festivals', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (146, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 147', '2026-06-07', 'Actividad 147 en Medellin con categoria Theater', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (147, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 148', '2026-06-08', 'Actividad 148 en Bogota con categoria Concerts', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (148, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 149', '2026-06-09', 'Actividad 149 en Manizales con categoria Workshops', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (149, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 150', '2026-06-10', 'Actividad 150 en Cartagena con categoria Conferences', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (150, 3);
INSERT INTO events_categories (event_id, category_id) VALUES (150, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 151', '2026-06-11', 'Actividad 151 en Bogota con categoria Sports', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (151, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 152', '2026-06-12', 'Actividad 152 en Medellin con categoria Gastronomy', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (152, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 153', '2026-06-13', 'Actividad 153 en Cali con categoria Festivals', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (153, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 154', '2026-06-14', 'Actividad 154 en Bogota con categoria Theater', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (154, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 155', '2026-06-15', 'Actividad 155 en Barranquilla con categoria Concerts', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (155, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 156', '2026-06-16', 'Actividad 156 en Bucaramanga con categoria Workshops', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (156, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 157', '2026-06-17', 'Actividad 157 en Medellin con categoria Conferences', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (157, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 158', '2026-06-18', 'Actividad 158 en Bogota con categoria Sports', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (158, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 159', '2026-06-19', 'Actividad 159 en Manizales con categoria Gastronomy', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (159, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 160', '2026-06-20', 'Actividad 160 en Cartagena con categoria Festivals', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (160, 6);
INSERT INTO events_categories (event_id, category_id) VALUES (160, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 161', '2026-06-21', 'Actividad 161 en Bogota con categoria Theater', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (161, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 162', '2026-06-22', 'Actividad 162 en Medellin con categoria Concerts', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (162, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 163', '2026-06-23', 'Actividad 163 en Cali con categoria Workshops', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (163, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 164', '2026-06-24', 'Actividad 164 en Bogota con categoria Conferences', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (164, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 165', '2026-06-25', 'Actividad 165 en Barranquilla con categoria Sports', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (165, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 166', '2026-06-26', 'Actividad 166 en Bucaramanga con categoria Gastronomy', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (166, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 167', '2026-06-27', 'Actividad 167 en Medellin con categoria Festivals', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (167, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 168', '2026-06-28', 'Actividad 168 en Bogota con categoria Theater', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (168, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 169', '2026-07-01', 'Actividad 169 en Manizales con categoria Concerts', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (169, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 170', '2026-07-02', 'Actividad 170 en Cartagena con categoria Workshops', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (170, 2);
INSERT INTO events_categories (event_id, category_id) VALUES (170, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 171', '2026-07-03', 'Actividad 171 en Bogota con categoria Conferences', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (171, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 172', '2026-07-04', 'Actividad 172 en Medellin con categoria Sports', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (172, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 173', '2026-07-05', 'Actividad 173 en Cali con categoria Gastronomy', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (173, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 174', '2026-07-06', 'Actividad 174 en Bogota con categoria Festivals', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (174, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 175', '2026-07-07', 'Actividad 175 en Barranquilla con categoria Theater', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (175, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 176', '2026-07-08', 'Actividad 176 en Bucaramanga con categoria Concerts', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (176, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 177', '2026-07-09', 'Actividad 177 en Medellin con categoria Workshops', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (177, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 178', '2026-07-10', 'Actividad 178 en Bogota con categoria Conferences', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (178, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 179', '2026-07-11', 'Actividad 179 en Manizales con categoria Sports', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (179, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 180', '2026-07-12', 'Actividad 180 en Cartagena con categoria Gastronomy', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (180, 5);
INSERT INTO events_categories (event_id, category_id) VALUES (180, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 181', '2026-07-13', 'Actividad 181 en Bogota con categoria Festivals', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (181, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 182', '2026-07-14', 'Actividad 182 en Medellin con categoria Theater', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (182, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 183', '2026-07-15', 'Actividad 183 en Cali con categoria Concerts', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (183, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 184', '2026-07-16', 'Actividad 184 en Bogota con categoria Workshops', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (184, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 185', '2026-07-17', 'Actividad 185 en Barranquilla con categoria Conferences', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (185, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 186', '2026-07-18', 'Actividad 186 en Bucaramanga con categoria Sports', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (186, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 187', '2026-07-19', 'Actividad 187 en Medellin con categoria Gastronomy', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (187, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 188', '2026-07-20', 'Actividad 188 en Bogota con categoria Festivals', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (188, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 189', '2026-07-21', 'Actividad 189 en Manizales con categoria Theater', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (189, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 190', '2026-07-22', 'Actividad 190 en Cartagena con categoria Concerts', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (190, 1);
INSERT INTO events_categories (event_id, category_id) VALUES (190, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 191', '2026-07-23', 'Actividad 191 en Bogota con categoria Workshops', 1, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (191, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 192', '2026-07-24', 'Actividad 192 en Medellin con categoria Conferences', 2, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (192, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 193', '2026-07-25', 'Actividad 193 en Cali con categoria Sports', 3, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (193, 4);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 194', '2026-07-26', 'Actividad 194 en Bogota con categoria Gastronomy', 4, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (194, 5);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 195', '2026-07-27', 'Actividad 195 en Barranquilla con categoria Festivals', 5, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (195, 6);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Festival Cultural 196', '2026-07-28', 'Actividad 196 en Bucaramanga con categoria Theater', 6, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (196, 7);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 197', '2026-08-01', 'Actividad 197 en Medellin con categoria Concerts', 7, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (197, 1);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Conferencia Tech 198', '2026-08-02', 'Actividad 198 en Bogota con categoria Workshops', 8, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (198, 2);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Evento Eventify 199', '2026-08-03', 'Actividad 199 en Manizales con categoria Conferences', 9, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (199, 3);
INSERT INTO events (nombre, fecha, descripcion, venue_id, active) VALUES ('Taller Profesional 200', '2026-08-04', 'Actividad 200 en Cartagena con categoria Sports', 10, TRUE);
INSERT INTO events_categories (event_id, category_id) VALUES (200, 4);
INSERT INTO events_categories (event_id, category_id) VALUES (200, 5);
